version: '3.8'

services:
  qualigpt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qualigpt-app
    ports:
      - "5005:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      # Optional: Mount for development (uncomment for dev mode)
      # - ./qualigpt-webapp.py:/app/qualigpt-webapp.py
      # - ./templates:/app/templates
      # For logs (optional)
      - qualigpt_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - qualigpt-network
    # Resource limits (optional, adjust based on your needs)
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # Optional: Add nginx reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   container_name: qualigpt-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - qualigpt
  #   restart: unless-stopped
  #   networks:
  #     - qualigpt-network

volumes:
  qualigpt_logs:
    driver: local

networks:
  qualigpt-network:
    driver: bridge

# Development override file usage:
# Create docker-compose.override.yml for development settings
# Example override for development:
# version: '3.8'
# services:
#   qualigpt:
#     environment:
#       - FLASK_ENV=development
#       - FLASK_DEBUG=1
#     volumes:
#       - ./:/app
#     command: ["python", "qualigpt-webapp.py"]
